name: PowerShell script
author: Freddy Kristiansen
permissions:
  contents: write
  pull-requests: write
inputs:
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentCorrelationId:
    description: Specifies the parent correlation Id for the Telemetry signal
    required: false
    default: ''       
  url:
    description: Direct Download Url of .app or .zip file
    required: true
  directCommit:
    description: Direct Commit (Y/N)
    required: false
    default: 'N'
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/AddExistingApp.ps1 -actor '${{ inputs.actor }}' -token '${{ inputs.token }}' -url '${{ inputs.url }}' -directCommit ('${{ inputs.directCommit }}' -eq 'Y')
      shell: PowerShell
branding:
  icon: terminal
  color: blue
